Git intro
CodeYourFuture/syllabus-archive pull request #338
Opened 2020-02-22 23:40 UTC by rarmatei

2020-02-22 23:44 UTC, rarmatei commented on introduction/week-2/lesson.md
> -* The executor will receive a command and the input needed to carry out the command (e.g. “COMPARE: is value in slot 3 is larger than value in slot 7?”)
Sorry for these! Just realised only after I committed that Prettier was running in the background and changed them.

Happy to revert them if you think it's worth it?

2020-02-23 23:03 UTC, bonboh requested changes
Great stuff @rarmatei! Left just a few comments. I thought of Google Docs when reading this since it has [revision history](https://docs.google.com/document/d/1woFw1WgUn7-xyYMMOTnWjYxqWQ-fceXIzgefjk3dEkw)—would it be useful to mention this as well as another example of creating snapshots?

2020-02-23 23:03 UTC, bonboh commented on introduction/week-2/git-workshop-transcript.md
> +So let's say our next task is to add a "Skills" section to our CV. We'll start by adding some skills, maybe decide to remove some, then add some more skills again, but once we're done and satisfied t
Minor nitpick: Would it be worth using the same online dictionary, e.g. changing this one (lexico) to merriam-webster for consistency?

2020-02-23 23:03 UTC, bonboh commented on introduction/week-2/git-workshop-transcript.md
> +The selected one, `job-application`, is our **latest** one. The one that has all the latest changes and is the most up to date. The other ones, contain different [milestones](https://www.merriam-webs
```suggestion
The selected one, `job-application`, is our **latest** one. It is the one that has all the latest changes and is the most up to date. The other ones, contain different [milestones](https://www.merriam-webster.com/dictionary/milestone) of our work, and they're named accordingly! There's a folder for our initial template (right before we first started writing) another one for when we added "Education" to our CV etc.
```

2020-02-23 23:03 UTC, bonboh commented on introduction/week-2/git-workshop-transcript.md
> +Turns out we do, but our robot is called Git. And whenever we want to use Git in a folder, to track our changes, we need to tell it to initialize in that folder.
```suggestion
Turns out we do, but our robot is called Git. And whenever we want to use Git in a folder, to track our changes, we need to first tell it to initialize in that folder.
```

2020-02-23 23:03 UTC, bonboh commented on introduction/week-2/git-workshop-transcript.md
> +1. Create a new folder with `mkdir`
```suggestion
1. Create a new folder with [`mkdir`](https://manpages.ubuntu.com/manpages/bionic/en/man1/mkdir.1posix.html)
```
Would it be useful to link to documentation? Maybe not if this Git section comes after the introduction to the terminal + commands

2020-02-23 23:03 UTC, bonboh commented on introduction/week-2/lesson.md
> -* The executor will receive a command and the input needed to carry out the command (e.g. “COMPARE: is value in slot 3 is larger than value in slot 7?”)
No problem, keep it prettied!

2020-02-23 23:03 UTC, bonboh commented on introduction/week-2/lesson.md
> +##### Workshop Exercises
```suggestion
### Workshop Exercises
```

2020-02-23 23:03 UTC, bonboh commented on introduction/week-2/lesson.md
> +###### Part 1
```suggestion
#### Part 1
```

2020-02-23 23:03 UTC, bonboh commented on introduction/week-2/lesson.md
> +###### Part 2
```suggestion
#### Part 2
```

2020-02-23 23:03 UTC, bonboh commented on introduction/week-2/lesson.md
> +###### Part 3
```suggestion
#### Part 3
```

2020-03-12 21:06 UTC, merged